-- Supabase Schema Definition
-- This file contains the CREATE TABLE statements for our project's database schema.
-- It serves as a single source of truth for our data structures,
-- making it easier for AI and humans to understand the database layout.

-- Table for logging the automation processes
CREATE TABLE public.automation_logs (
    id bigint NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    run_id uuid NOT NULL,
    level text NOT NULL CHECK (level IN ('INFO', 'SUCCESS', 'WARN', 'ERROR')),
    message text,
    metadata jsonb
);

-- Enable Row Level Security
ALTER TABLE public.automation_logs ENABLE ROW LEVEL SECURITY;

-- Create policies for access
-- For now, we only allow service_role to write, and authenticated users to read.
-- This can be adjusted based on security requirements.
CREATE POLICY "Allow authenticated read access"
ON public.automation_logs
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow service_role to insert"
ON public.automation_logs
FOR INSERT
WITH CHECK (true);

-- Comments for clarity
COMMENT ON TABLE public.automation_logs IS 'Stores log entries for all automated processes, like cron jobs.';
COMMENT ON COLUMN public.automation_logs.run_id IS 'A unique identifier for a single run of a specific cron job.';
COMMENT ON COLUMN public.automation_logs.level IS 'The severity level of the log entry.';
COMMENT ON COLUMN public.automation_logs.metadata IS 'A JSON object for storing additional structured data, like account_name or product_id.';


-- =============================================================================
-- Core Application Tables
-- =============================================================================

-- Table for storing account information
create table public.accounts_duplicate (
  name text not null,
  created_at timestamp with time zone null default CURRENT_TIMESTAMP,
  updated_at timestamp with time zone null default CURRENT_TIMESTAMP,
  待上架 jsonb null,
  点赞队列 text[] null,
  已点赞 text[] null,
  关键词prompt text null,
  业务描述 text null,
  xhs_account text null,
  闲鱼账号 text null,
  手机型号 text null,
  文案生成prompt text null,
  scheduling_rule jsonb null, -- Rule for auto-scheduling, e.g. {"enabled": true, "items_per_day": 5}
  xhs_头像 text null,
  上架时间 timestamp with time zone null,
  已上架json jsonb null,
  display_order integer null,
  constraint accounts_duplicate_pkey primary key (name)
) TABLESPACE pg_default;

COMMENT ON COLUMN public.accounts_duplicate."已上架json" IS 'Stores products that have been listed. JSON array format: [{"id": <product_id>, "上架时间": "<timestamp>"}]';
COMMENT ON COLUMN public.accounts_duplicate."待上架" IS 'Stores products scheduled for listing. JSON array format: [{"id": <product_id>, "scheduled_at": "<timestamp>"}]';
COMMENT ON COLUMN public.accounts_duplicate.scheduling_rule IS 'Rule for auto-scheduling, e.g. {"enabled": true, "items_per_day": 5}';

-- Table for the main product library
create table public.search_results_duplicate_本人 (
  id integer not null default nextval('search_results_id_seq'::regclass),
  keyword text null,
  result_image_url text null,
  result_text_content text null,
  is_electronic boolean null,
  created_at timestamp with time zone null default CURRENT_TIMESTAMP,
  修改后文案 text null,
  价格 text null,
  ai提取关键词 text null,
  type text null,
  账号分类 text null,
  建议投放账号 text null,
  上架时间 timestamp with time zone null,
  keywords_extracted_at timestamp with time zone null,
  keywords_finalized_at timestamp with time zone null,
  product_url text null,
  -- New fields for the AI review pipeline
  ai_review_status text null default 'pending'::text,
  ai_review_comments text null,
  ai_reviewed_at timestamp with time zone null,
  is_ai_generated boolean null default false, -- New flag for our automation
  constraint search_results_duplicate_本人_pkey primary key (id),
  constraint search_results_duplicate_本人_type_fkey foreign KEY (type) references accounts_duplicate (name),
  constraint search_results_duplicate_本人_账号分类_fkey foreign KEY ("账号分类") references accounts_duplicate (name)
) TABLESPACE pg_default;

-- Table for account-specific important keywords
create table public.important_keywords_本人 (
  id bigint generated by default as identity not null,
  account_name text not null,
  keyword text null,
  created_at timestamp with time zone not null default now(),
  search_executed_at timestamp with time zone null,
  search_history jsonb null default '[]'::jsonb,
  constraint important_keywords_本人_pkey primary key (id),
  constraint uq_account_keyword unique (account_name, keyword),
  constraint fk_account_name foreign KEY (account_name) references accounts_duplicate (name) on delete CASCADE
) TABLESPACE pg_default;

-- Table for tracking product scheduling details
-- This table provides a more structured alternative to the "待上架" JSON blob in accounts_duplicate

-- =============================================================================
-- Automation & Logging Tables
-- =============================================================================

-- Table to track the status of currently running automation tasks
CREATE TABLE public.automation_runs (
  id bigint NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  account_name text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'running',
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fk_account_name FOREIGN KEY (account_name) REFERENCES public.accounts_duplicate(name) ON DELETE CASCADE
);

COMMENT ON TABLE public.automation_runs IS 'Tracks currently active automation runs to prevent concurrency issues and provide real-time status.';
COMMENT ON COLUMN public.automation_runs.account_name IS 'The account currently being processed. UNIQUE constraint ensures only one run per account at a time.';

