name: Trigger Vercel Cron Job

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  trigger-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Cron Endpoint
        run: |
          curl --request GET \
            --url 'https://list-five-ruddy.vercel.app/api/trigger-job' \
            --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}' 